name: CI

on:
  push:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.62
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Test
        run: go test ./...
